spring.application.name=SmartMallParking
# MySQL connection
spring.datasource.url=jdbc:mysql://localhost:3306/smart_mall_parking
spring.datasource.username=root
spring.datasource.password=root

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server
server.port=8080
